# docker-compose.test.yml
version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - portal-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - portal-redis:/var/lib/redis/data

  portal:
    image: $DOCKER_USERNAME/portal:latest
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    image: $DOCKER_USERNAME/portal:latest
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    image: $DOCKER_USERNAME/portal-nginx:latest
    links:
      - portal
    ports:
      - '8020:8020'

volumes:
  portal-postgres:
  portal-redis:
