version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5433:5432'
    volumes:
      - portal-postgres:/var/lib/postgresql/portal_data

  redis:
    image: redis:5.0.7
    ports:
      - '6370:6379'
    volumes:
      - portal-redis:/var/lib/redis/portal_data

  portal:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./portal
        target: /opt/app/portal
      - bundle_cache:/usr/local/bundle
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./portal
        target: /opt/app/portal
      - bundle_cache:/usr/local/bundle
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - portal
    volumes:
      - bundle_cache:/usr/local/bundle
    ports:
      - '8020:8020'

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

  webpacker:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    depends_on:
      - portal
    volumes:
      - type: bind
        source: ./portal
        target: /opt/app/portal
      - bundle_cache:/usr/local/bundle
    ports:
      - '3035:3035'
    env_file:
      - .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  portal-postgres:
  portal-redis:
  bundle_cache:
